---
- hosts: home
  gather_facts: no

  pre_tasks:
    - import_tasks: tasks/ssh_juggle_port.yml
      tags:
        - port

- hosts: home
  tasks:
    - import_tasks: tasks/user.yml
      tags:
        - user


# PiHole/IKEv2 server
- hosts: coda
  become: yes
  roles:
    - role: essential
      tags: 
        - essential

    - role: docker
      tags: 
        - docker

    # MSMTP (for SMART notifications)
    - role: chriswayg.msmtp-mailer
      tags: 
        - msmtp

    - role: oefenweb.dns
      tags:
        - dns

    - role: ddclient
      when: enable_ddclient | default(False)
      tags:
        - ddclient

    - role: duckdns
      when: enable_duckdns | default(False)
      tags:
        - duckdns 

    - role: containers/cloudflare-ddns
      tags: 
        - cloudflare-ddns
        - containers
      when: enable_cloudflare | default(False)


    - role: containers/pihole
      when: enable_pihole | default(False)
      tags:
        - pihole 
        - containers

    - role: containers/ikev2
      when: enable_ikev2 | default(False)
      tags:
        - containers
        - ikev2 

    # NTP
    - role: geerlingguy.ntp
      tags: 
        - ntp

    # SSH security (at the end because it breaks SSH connection)
    - role: geerlingguy.security
      tags: 
        - security



# Home server/NAS
- hosts: fragile
  become: yes

  pre_tasks:
    - name: Remove snap functionality
      import_tasks: tasks/yeet_snaps.yml
      tags: nosnaps

  roles:
    - role: essential
      tags: 
        - essential

    - role: fail2ban
      tags:
      - fail2ban

    - role: filesystems/mergerfs
      tags:
      - mergerfs
      
    - role: filesystems/mounts
      tags:
        - mounts
    # MSMTP (for SMART notifications)
    - role: chriswayg.msmtp-mailer
      tags: 
        - msmtp

    - role: docker
      tags: 
        - docker

    - role: oefenweb.dns
      tags:
        - dns

    - role: ironicbadger.ansible_role_snapraid
      tags:
      - snapraid

    - role: filesystems/hd-idle
      tags:
      - hd-idle
      
    # SMART error checking
    - role: stuvusit.smartd
      tags:
      - smartd

    - role: avahi
      tags: 
        - avahi

    - role: containers/watchtower
      tags:
        - watchtower
        - containers

    - role: containers/unifi
      tags:
        - unifi
        - containers
      when: enable_unifi | default(False)

    - role: containers/pihole
      when: enable_pihole | default(False)
      tags:
        - pihole 
        - containers

    - role: containers/authelia
      tags:
        - authelia
        - containers
      when: enable_authelia | default(False)

    - role: containers/youtransfer
      tags:
        - youtransfer
        - containers
      when: enable_youtransfer | default(False)


    - role: containers/swag
      tags: 
        - swag
        - containers
      when: enable_swag | default(False)

    - role: containers/bitwarden
      tags:
        - bitwarden
        - containers
      when: enable_bitwarden | default(False)
    
    - role: containers/deluge
      tags: 
        - deluge
        - containers
      when: enable_deluge | default(False)

    - role: homer
      tags: 
        - homer
        - containers
      when: enable_homer | default(False)

    - role: containers/flame
      tags: 
        - flame
        - containers
      when: enable_flame | default(False)

    - role: containers/nextcloud
      tags: 
        - nextcloud
        - containers
      when: enable_nextcloud | default(False)

    - role: containers/jackett
      tags: 
        - jackett
        - containers
      when: enable_jackett | default(False)

    - role: containers/sonarr
      tags: 
        - sonarr
        - containers
      when: enable_sonarr | default(False)

    - role: containers/readarr
      tags: 
        - readarr
        - containers
      when: enable_readarr | default(False)

    - role: containers/lidarr
      tags: 
        - lidarr
        - containers
      when: enable_lidarr | default(False)

    - role: containers/radarr
      tags: 
        - radarr
        - containers
      when: enable_radarr | default(False)

    - role: containers/booksonic
      tags: 
        - booksonic
        - containers
      when: enable_booksonic | default(False)

    - role: containers/plex
      tags: 
        - plex
        - containers
      when: enable_plex | default(False)

    - role: containers/jellyfin
      tags: 
        - jellyfin
        - containers
      when: enable_jellyfin | default(False)

    - role: containers/photoprism
      tags: 
        - photoprism
        - containers
      when: enable_photoprism | default(False)

    - role: containers/wireguard
      tags: 
        - wireguard
        - containers
      when: enable_wireguard | default(False)

    - role: containers/openbooks
      tags: 
        - openbooks
        - containers
      when: enable_openbooks | default(False)

    - role: containers/deconz
      tags: 
        - deconz
        - smarthome
        - containers
      when: enable_deconz | default(False)

    - role: containers/homeassistant
      tags: 
        - homeassistant
        - smarthome
        - containers
      when: enable_homeassistant | default(False)

    # Samba
    - role: bertvv.samba
      tags: 
        - samba

    # NTP
    - role: geerlingguy.ntp
      tags: 
        - ntp

    # SSH security (at the end because it breaks SSH connection)
    - role: geerlingguy.security
      tags: 
        - security
