---
#
# Tasks and roles for all hosts
#
- hosts: fleet
  gather_facts: no

  pre_tasks:
    - import_tasks: tasks/ssh_juggle_port.yml
      tags:
        - port

- hosts: fleet
  become: yes
  roles:

    - role: system
      tags: 
        - system

    - role: docker
      tags: 
        - docker

    - role: security/fail2ban
      tags:
      - fail2ban

    - role: chriswayg.msmtp-mailer
      tags: 
        - msmtp

    - role: oefenweb.dns
      tags:
        - dns

    - role: geerlingguy.ntp
      tags: 
        - ntp

    - role: geerlingguy.security
      tags: 
        - security


#
# PiHole/IKEv2 server
#
- hosts: coda
  become: yes
  roles:
    - role: network/ddclient
      when: enable_ddclient | default(False)
      tags:
        - ddclient

    - role: network/duckdns
      when: enable_duckdns | default(False)
      tags:
        - duckdns 

    - role: network/cloudflare-ddns
      tags: 
        - cloudflare-ddns
        - containers
      when: enable_cloudflare | default(False)

    - role: network/pihole
      when: enable_pihole | default(False)
      tags:
        - pihole 
        - containers

    - role: network/ikev2
      when: enable_ikev2 | default(False)
      tags:
        - containers
        - ikev2 

#
# Home server/NAS
#
- hosts: fragile
  become: yes

  roles:

    #
    # Filesystems
    #
    - role: filesystems/mergerfs
      tags:
      - mergerfs
      
    - role: filesystems/mounts
      tags:
        - mounts

    - role: filesystems/hd-idle
      tags:
      - hd-idle

    - role: stuvusit.smartd
      tags:
      - smartd

    - role: ironicbadger.ansible_role_snapraid
      tags:
      - snapraid

    #
    # Network
    #
    - role: network/avahi
      tags: 
        - avahi

    - role: network/wireguard
      tags: 
        - wireguard
        - containers
      when: enable_wireguard | default(False)

    - role: network/swag
      tags: 
        - swag
        - containers
      when: enable_swag | default(False)

    #
    # Homer
    # 
    - role: homer
      tags: 
        - homer
        - containers
      when: enable_homer | default(False)

    #
    # Services
    #
    - role: containers/system/jackett
      tags: 
        - jackett
        - containers
      when: enable_jackett | default(False)

    - role: containers/system/authelia
      tags:
        - authelia
        - containers
      when: enable_authelia | default(False)

    - role: containers/system/watchtower
      tags:
        - watchtower
        - containers

    - role: containers/system/unifi
      tags:
        - unifi
        - containers
      when: enable_unifi | default(False)

    #
    # Media
    #
    - role: containers/media/deluge
      tags: 
        - deluge
        - containers
      when: enable_deluge | default(False)

    - role: containers/media/sonarr
      tags: 
        - sonarr
        - containers
      when: enable_sonarr | default(False)

    - role: containers/media/radarr
      tags: 
        - radarr
        - containers
      when: enable_radarr | default(False)

    - role: containers/media/booksonic
      tags: 
        - booksonic
        - containers
      when: enable_booksonic | default(False)

    - role: containers/media/plex
      tags: 
        - plex
        - containers
      when: enable_plex | default(False)

    - role: containers/media/jellyfin
      tags: 
        - jellyfin
        - containers
      when: enable_jellyfin | default(False)

    - role: containers/media/openbooks
      tags: 
        - openbooks
        - containers
      when: enable_openbooks | default(False)

    #
    # Services
    #
    - role: containers/services/photoprism
      tags: 
        - photoprism
        - containers
      when: enable_photoprism | default(False)

    - role: containers/services/nextcloud
      tags: 
        - nextcloud
        - containers
      when: enable_nextcloud | default(False)

    - role: containers/services/vaultwarden
      tags:
        - vaultwarden
        - containers
      when: enable_vaultwarden | default(False)
 
    #
    # Home automation
    #
    - role: containers/homeautomation/deconz
      tags: 
        - deconz
        - smarthome
        - containers
      when: enable_deconz | default(False)

    - role: containers/homeautomation/homeassistant
      tags: 
        - homeassistant
        - smarthome
        - containers
      when: enable_homeassistant | default(False)

    #
    # Samba
    #
    - role: bertvv.samba
      tags: 
        - samba