#
# Process-exporter
#

- name: Install python3 and pip
  package:
    name:
      - python3
      - python3-pip
    state: latest

- name: Install github3 module
  pip:
    name: 
      - github3.py

- name: Check if process-exporter is installed
  command:
    cmd: which process-exporter
  register: process_exporter
  changed_when: False
  failed_when: False
  
- name: Check the process-exporter version if installed
  shell:
    cmd: "process-exporter --version | grep -o '[0-9]\\.[0-9]*\\.[0-9]*'"
  register: process_exporter_version
  when: process_exporter.rc == 0
  changed_when: False

- name: Set current process-exporter version to 0 if not installed
  set_fact:
    process_exporter_version:
      stdout: "0"
  when: process_exporter.rc == 1

- name: Check latest process-exporter release
  github_release:
    user: ncabatoff
    repo: process-exporter
    action: latest_release
    token: "{{ github_token }}"
  register: process_exporter_release
  changed_when: process_exporter_release.tag != ("v" + process_exporter_version.stdout)

- name: Install latest process-exporter
  apt: 
    deb: "https://github.com/ncabatoff/process-exporter/releases/download/{{ process_exporter_release.tag }}/process-exporter_{{ process_exporter_release.tag | regex_replace('^v','') }}_linux_{{ arch }}.deb"
  when: process_exporter_release.tag != ("v" + process_exporter_version.stdout)

#
# Smartmon
#
- name: Install moreutils
  package:
    name: moreutils
    state: latest

- name: Download smartmon.py
  get_url:
    url: https://raw.githubusercontent.com/prometheus-community/node-exporter-textfile-collector-scripts/master/smartmon.py
    dest: /usr/local/bin
    mode: 0755
    owner: root
    group: root

- name: Make sure the text output directory exists
  file:
    path: /etc/node_exporter
    state: directory
    recurse: true
    owner: root
    group: root
    mode: 0755

- name: Install the systemd service
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item | basename }}"
    owner: root
    group: root
    mode: 0755
  notify: 
    - monitoring systemd reload
  with_fileglob:
    - files/monitoring/*.service
    - files/monitoring/*.timer
 
- name: Start and enable the systemd services
  systemd:
    state: started
    enabled: true
    name: "{{ item }}"
  with_items:
    - smartmon.timer
    - process-exporter

- name: Modify the `node_exporter_options` variable
  set_fact:
    node_exporter_options: '--no-collector.diskstats --collector.textfile.directory=/etc/node_exporter'
