---
- name: Make sure the {{ container_name }} container is created and running
  docker_container:
      name: '{{ container_name }}'
      image: pawelmalak/flame:multiarch2.2.1
      networks:
          - name: swag_internal_macvlan
            ipv4_address: '{{ ip_address }}'
      pull: yes
      state: 'started'
      volumes:
          - '{{ docker_dir }}/{{ container_name }}/custom.css:/app/public/flame.css'
          - '{{ docker_dir }}/{{ container_name }}/fonts:/app/public/static/media'
          - '{{ docker_dir }}/{{ container_name }}/data:/app/data'
          - '/var/run/docker.sock:/var/run/docker.sock'
      restart_policy: unless-stopped
