---
- name: Get infos on the swag containers
  docker_container_info:
    name: "{{ item }}"
  register: swag_docker_status
  with_items:
    - swag_internal
    - swag_public

- name: Does internal container exist?
  set_fact:
    swag_internal_exists: yes
  when: swag_docker_status.results[0].exists

- name: Does public container exist?
  set_fact:
    swag_public_exists: yes
  when: swag_docker_status.results[1].exists

- name: Is internal container running?
  set_fact:
    swag_internal_running: yes
  when: swag_internal_exists is defined and swag_docker_status.results[0].container['State']['Running'] 

- name: Is public container running?
  set_fact:
    swag_internal_running: yes
  when: swag_public_exists is defined and swag_docker_status.results[1].container['State']['Running'] 
